### ISSUE TITLE
categories fail

### ISSUE THREAD

**Issue by polluks** [otto-de/marketplace-php-sdk#3]
````
php.exe SampleCli.php -e live -u api_*** -p *** categories
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in ...\generated\products\ObjectSerializer.php on line 286

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in ...\generated\products\ObjectSerializer.php on line 286
````
See https://stackoverflow.com/questions/561066/fatal-error-allowed-memory-size-of-134217728-bytes-exhausted-codeigniter-xml
Right now the output is 360,415 bytes

**Comment by marcogreiveldinger** [comment]
Thanks for reporting the issue. Definitely a bug in the sdk.

This happens due to a large amount of category data which is fetched. It should be done page by page and the client/user should decide what to do with the pages.
Right now the sdk cycles through every page and creates an array of all category data, which (I already wrote it) is huge.

**Comment by torstenbeuck0815** [comment]
Hi and sorry for the very long time this issue has stayed unresolved yet. We just started working on this. The solution is that the SDK method _getCategories_ will return an Iterator in the future, which can then be used to iterate over the list of all categories via foreach. Therefore an optional parameter $pageSize will be introduced with which the client can control the memory footprint and the number of GET requests that will be generated.
The change should be published in the next few days.
