### ISSUE TITLE
attributes support

### ISSUE THREAD

**Issue by polluks** [otto-de/marketplace-php-sdk#4]
<s>**Is your feature request related to a problem? Please describe.**
If you have a category, you always want to know its attributes.

**Describe the solution you'd like**
How about an optional parameter for `getCategoryDefinition`?</s>

Well, it's already implemented in `category`.
Maybe you should add a hint about the calling convention
`... categories`
`foo->bar`

`... category bar`

**Comment by marcogreiveldinger** [comment]
Hi @polluks 

as you already found out it is possible to query a single category with all its attributes. Unluckily there is no single endpoint available for that yet, so there is this workaround to load all categories and look for the single searched one.

This is not working currently because of issue #3 ... 
We will change the behaviour and will give a ping here when it is working again!

**Comment by torstenbeuck0815** [comment]
After fixing #3 this now works as expected.
